config/routes.rb
Rails.application.routes.draw do

  resource :contact

  resources :leads, only: [:index]

  resources :products do
    member do
      resource :appointment, module: "products", only: [:show, :create]
    end
  end

  resources :users

  root "pages#home"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ApplicationRecord
  has_many :leads
end

app/models/products/appointment_form.rb
class Products::AppointmentForm
  include ActiveModel::Model

  attr_accessor :name, :email, :body, :product_id, :join_mailing_list

  validates :name, :email, presence: true

  def initialize(attributes={})
    Rails.logger.info("product_id was missing in appointment-form")
    super
  end

  def submit
    if valid?
      # Do something on success, such as:
      # - initiating the logic to take care of the user.
      # - sending email async
      # - adding it to statistics

      begin
        Lead.create!(lead_type: "appointment", lead_source: "website", product_id: product_id)
      rescue RuntimeError => error
        Rails.logger.error("Error creating a lead: #{error}")
      end

      true
    else
      false
    end
  end

  def join_mailing_list
    ActiveRecord::Type::Boolean.new.cast(@join_mailing_list)
  end
end

app/controllers/products/appointments_controller.rb
class Products::AppointmentsController < ApplicationController
  before_action :set_product

  def show
    @appointment_form = Products::AppointmentForm.new(product_id: params[:id])
  end

  def create
    @appointment_form = Products::AppointmentForm.new(appointment_form_params)
    if @appointment_form.submit
      redirect_to root_path, notice: "Your appointment request was sent! Thanks!"
    else
      render action: :show
    end
  end

  private

    def appointment_form_params
      params.require(:products_appointment_form).permit(:name, :email, :body, :product_id, :join_mailing_list)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td style="background: <%= product.description %>;"><%= product.description %></td>
          <td><%= link_to 'Appointment', appointment_path(product) %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Make an appointment', appointment_path(@product) %> |
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>