config/routes.rb
Rails.application.routes.draw do

  resource :contact

  resources :leads, only: [:index]

  resources :products do
    member do
      resource :appointment, module: "products", only: [:show, :create]
    end
  end

  resources :users

  root "pages#home"
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="<%= flash_classlist(type) %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to base_title, root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= current_page?(root_path) && 'active' %>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= current_page?(users_path) && 'active' %>">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= current_page?(products_path) && 'active' %>">
        <%= link_to "Products", products_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= current_page?(leads_path) && 'active' %>">
        <%= link_to "Leads", leads_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= current_page?(contact_path) && 'active' %>">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= base_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/top_nav" %>
    <%= render "layouts/flash" %>

    <div class="my-sm-3"></div>

    <main class="container">
      <%= yield %>

      <% if Rails.env.development? %>
        <div class="my-sm-3"></div>
        <div class="card card-block">
          <%= debug(params) %>
        </div>
      <% end  %>
    </main>

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>